### ISSUE TITLE
Attribute error _enter_ when running int8 compilation

### ISSUE THREAD

**Issue by harishprabhala** [rmccorm4/tensorrt-utils#37]
I am getting this error while compiling for int8. The same code works fine for FP32 and FP16

```
[05/31/2022-05:46:12] [TRT] [E] 1: Unexpected exception 
Traceback (most recent call last):
  File "./onnx_to_tensorrt.py", line 218, in <module>
    main()
  File "./onnx_to_tensorrt.py", line 213, in main
    with builder.build_engine(network, config) as engine, open(args.output, "wb") as f:
AttributeError: __enter__
```

**Comment by CharlesNord** [comment]
I finally solved the problem, 

Just delete the `pycuda.autoinit` in `ImagenetCalibrator.py`  and add it in the beginning of the `onnx_to_tensor.py` the generated engine should live in the CUDA context created by the pycuda
